### ISSUE TITLE
requireNativeComponent: "SvgView" was not found in the UIManager

### ISSUE THREAD

**Issue by KonstntinM** [troZee/react-native-svg-view#10]
Hello everyone, 

first of all thank you for developing the package. 
While experimenting with the package, I ran into a bug that I can't explain. When I include the package exactly as in the example, I get the following error: "requireNativeComponent: "SvgView" was not found in the UIManager."

## error message

![Error screen on the test device](https://i.ibb.co/pZpfCTT/img.png)

## code 
My code looks like this.

```javascript
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

import SvgView from 'react-native-svg-view'

export default function NavigationBar() {
  return (
    <View style={styles.container}>
      <SvgView source="https://www.dropbox.com/s/d1dbdvo4l7xry4w/downdogflip.svg?raw=1" style={{ height: 24, width: 24 }}/>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    width: 375,
    height: 80,
    bottom: 0,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
});
```

## test environment

- iPhone 7 with IOS 13.5.1
- Expo Go Version 2.18.4
- Expo Version ~40.0.0
- Package Version ^12.1.0

Have any of you had the same problem? I would be glad to get some feedback.

**Comment by troZee** [comment]
Hey 👋 
Thank you for reporting an issue. What version of lib you are using ? The latest is https://www.npmjs.com/package/react-native-svg-view/v/0.1.6 

I checked example in the project and everything works fine 

![Simulator Screen Shot - iPhone 11 - 2021-01-29 at 15 19 58](https://user-images.githubusercontent.com/12766071/106286265-bb535c00-6245-11eb-8f96-9077fa6247c2.png)

**Comment by troZee** [comment]
I also created a fresh project and everything works fine. Maybe it is related to expo ? 

How about an android ? 
You can also try to go to ios folder and run pod install

**Comment by KonstntinM** [comment]
Okay, I just tested my project on an Android device as well and got the same error message. I am also using the latest package version (0.1.6) and have reinstalled all packages using expo installer.

I would now also assume that this is a problem with expo.

**Comment by troZee** [comment]
@KonstntinM 
Answer is here https://stackoverflow.com/questions/41597414/can-you-add-libraries-with-native-dependencies-to-an-expo-react-native-project

**Comment by KonstntinM** [comment]
Thanks a lot!
