### ISSUE TITLE
Android app crashing

### ISSUE THREAD

**Issue by tasacsachin** [troZee/react-native-svg-view#26]
If we pass svg uri that is not able to load then on android app crashing

 <SvgView
                        source={'https://truelayer-client-logos.s3-eu-west-1.amazonaws.com/banks/banks-icons/Santanders-icon.svg'}
                        style={style}
                    />

In iOS its working fine...nothing shows on the svg but on android app crashed

**Comment by troZee** [comment]
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>PW0QABQJMB2X3718</RequestId>
<HostId>wR87fV0OM5XUg9ol1u0YtoElaoV9+kRkLj+6w19MUtCKlkfjVe2w/gb9q5CnMjlzKvfh2YP6qVk=</HostId>
</Error>
```

It seems, the resource is protected
